The dataset used is a customer churn dataset from kaggle

In [1]:
# Importing important libraries
import pandas as pd
from sklearn.linear_model import LogisticRegression # Classification model 
from sklearn.model_selection import train_test_split 

data=pd.read_csv("C:/Users/Rajeev/Downloads/churn1.csv")
# Exploratory Data Analysis
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,CUST00001,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,CUST00002,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,...,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,CUST00003,Female,No,No,No,42.0,Yes,Yes,DSL,No,...,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,CUST00004,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,...,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,CUST00005,Male,Yes,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,...,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

In [2]:
data.describe()

             tenure  MonthlyCharges
count  69433.000000    69612.000000
mean      30.516858       60.588548
std       89.873767      111.509588
min      -10.000000       18.000000
25%       10.000000       29.670000
50%       20.000000       41.190000
75%       35.000000       63.882500
max      999.000000     1499.770000

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        70000 non-null  object
 1   gender            69252 non-null  object
 2   SeniorCitizen     69341 non-null  object
 3   Partner           66470 non-null  object
 4   Dependents        66435 non-null  object
 5   tenure            69433 non-null  float64
 6   PhoneService      70000 non-null  object
 7   MultipleLines     68132 non-null  object
 8   InternetService   70000 non-null  object
 9   OnlineSecurity    67078 non-null  object
 10  OnlineBackup      67253 non-null  object
 11  DeviceProtection  67106 non-null  object
 12  TechSupport       67267 non-null  object
 13  StreamingTV       67173 non-null  object
 14  StreamingMovies   67215 non-null  object
 15  Contract          70000 non-null  object
 16  PaperlessBilling  70000 non-null  object
 17  PaymentMethod     66431 non-null  object
 18  MonthlyCharges    69612 non-null  float64
 19  TotalCharges      68938 non-null  object
 20  Churn             70000 non-null  object
dtypes: float64(2), object(19)
memory usage: 11.2+ MB

In [4]:
data.dtypes

customerID           object
gender               object
SeniorCitizen        object
Partner              object
Dependents           object
tenure              float64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [5]:
# Data Cleaning & Data Preprocessing
data.isnull().sum()
# CLeaning this dataset will involve drop the columns which is not needed to proceed,fixing missing values and update the datatypes if they are not suitable for the data it is holding

customerID             0
gender               748
SeniorCitizen        659
Partner             3530
Dependents          3565
tenure               567
PhoneService           0
MultipleLines       1868
InternetService        0
OnlineSecurity      2922
OnlineBackup        2747
DeviceProtection    2894
TechSupport         2733
StreamingTV         2827
StreamingMovies     2785
Contract               0
PaperlessBilling       0
PaymentMethod       3569
MonthlyCharges       388
TotalCharges        1062
Churn                  0
dtype: int64

In [6]:
# Stage 1 : Dropping the unnecessary columns
data=data.drop(columns=['customerID'],axis=1) 
data.head()
# Dropped 'customerID' column because it adds no predictive value
# Dropped TotalCharges
print(data['SeniorCitizen'].unique())
print(data['SeniorCitizen'].dtype)

['0' '1' 'No' 'Yes' nan 'not senior']
object

In [11]:
# From the dataset we can see that in the SeniorCitizen column, some values are in the form of 0's and 1's while some are in Yes or No
# To clean this, we need to standardize the value to ensure that the column is holding the standard values
# To do this , we need to map the values

senior_mapping={'0': 0,'1': 1,'No': 0,'Yes': 1,'not senior': 0}
data['SeniorCitizen'] = (data['SeniorCitizen'].astype(str).str.strip().map(senior_mapping).astype('Int64'))
data.head()

# The column was a mix of Strings, numeric values and NaNs. To fix this we standardize the value bu first converting the whole column to a string datatype,
# Then we remove the hidden spaces if they are present, thn w use the map function to standardize the values then we handle the NaN values with the fillna() function
# Then finally we convert everything to integer data type, hence standardizing the entire column

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Male,0,No,Yes,3.0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,68.61,205.83,Yes
1,Male,1,Yes,No,2.0,Yes,Yes,DSL,No,No,No internet service,Yes,NaN,No,One year,Yes,Bank transfer (automatic),23.15,46.3,No
2,Female,0,No,No,42.0,Yes,Yes,DSL,No,Yes,No,NaN,Yes,Yes,Month-to-month,No,Electronic check,42.63,1790.46,Yes
3,Female,0,No,Yes,40.0,Yes,Yes,Fiber optic,No,No,Yes,No,No,No internet service,Month-to-month,No,Electronic check,75.04,3001.6,No
4,Male,1,Yes,Yes,17.0,Yes,NaN,Fiber optic,Yes,No,Yes,No,No internet service,No,Two year,Yes,Electronic check,22.38,380.46,Yes

In [15]:
cols=['OnlineSecurity','OnlineBackup','DeviceProtection','InternetService','TechSupport','StreamingTV','StreamingMovies']
for col in cols:
    data[col]=data[col].fillna("No")

# Here in the above selected columns we had diffrent values like "No Internet Service" and mostly "No". Both of these values in the end indicate the same thing that is "No"
# To fix this we will handle the columns selected above and change all the values to "NO" to standardize the column

In [16]:
data.isnull().sum()

gender               748
SeniorCitizen          0
Partner             3530
Dependents          3565
tenure               567
PhoneService           0
MultipleLines       1868
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
Contract               0
PaperlessBilling       0
PaymentMethod       3569
MonthlyCharges       388
TotalCharges        1062
Churn                  0
dtype: int64